// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: my.proto
// </auto-generated>
// https://protogen.marcgravell.com
// https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/grpc_api/bilibili/community/service/dm/v1/dm.proto

namespace DanmakuPlayer.Resources;

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192

[global::ProtoBuf.ProtoContract()]
public partial class Avatar : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"id")]
    [global::System.ComponentModel.DefaultValue("")]
    public string Id { get; set; } = "";

    [global::ProtoBuf.ProtoMember(2, Name = @"url")]
    [global::System.ComponentModel.DefaultValue("")]
    public string Url { get; set; } = "";

    [global::ProtoBuf.ProtoMember(3, Name = @"avatar_type")]
    public AvatarType AvatarType { get; set; }

}

[global::ProtoBuf.ProtoContract()]
public partial class Bubble : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"text")]
    [global::System.ComponentModel.DefaultValue("")]
    public string Text { get; set; } = "";

    [global::ProtoBuf.ProtoMember(2, Name = @"url")]
    [global::System.ComponentModel.DefaultValue("")]
    public string Url { get; set; } = "";

}

[global::ProtoBuf.ProtoContract()]
public partial class BubbleV2 : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"text")]
    [global::System.ComponentModel.DefaultValue("")]
    public string Text { get; set; } = "";

    [global::ProtoBuf.ProtoMember(2, Name = @"url")]
    [global::System.ComponentModel.DefaultValue("")]
    public string Url { get; set; } = "";

    [global::ProtoBuf.ProtoMember(3, Name = @"bubble_type")]
    public BubbleType BubbleType { get; set; }

    [global::ProtoBuf.ProtoMember(4, Name = @"exposure_once")]
    public bool ExposureOnce { get; set; }

    [global::ProtoBuf.ProtoMember(5, Name = @"exposure_type")]
    public ExposureType ExposureType { get; set; }

}

[global::ProtoBuf.ProtoContract()]
public partial class Button : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"text")]
    [global::System.ComponentModel.DefaultValue("")]
    public string Text { get; set; } = "";

    [global::ProtoBuf.ProtoMember(2, Name = @"action")]
    public int Action { get; set; }

}

[global::ProtoBuf.ProtoContract()]
public partial class BuzzwordConfig : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"keywords")]
    public global::System.Collections.Generic.List<BuzzwordShowConfig> Keywords { get; } = new global::System.Collections.Generic.List<BuzzwordShowConfig>();

}

[global::ProtoBuf.ProtoContract()]
public partial class BuzzwordShowConfig : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"name")]
    [global::System.ComponentModel.DefaultValue("")]
    public string Name { get; set; } = "";

    [global::ProtoBuf.ProtoMember(2, Name = @"schema")]
    [global::System.ComponentModel.DefaultValue("")]
    public string Schema { get; set; } = "";

    [global::ProtoBuf.ProtoMember(3, Name = @"source")]
    public int Source { get; set; }

    [global::ProtoBuf.ProtoMember(4, Name = @"id")]
    public long Id { get; set; }

    [global::ProtoBuf.ProtoMember(5, Name = @"buzzword_id")]
    public long BuzzwordId { get; set; }

    [global::ProtoBuf.ProtoMember(6, Name = @"schema_type")]
    public int SchemaType { get; set; }

}

[global::ProtoBuf.ProtoContract()]
public partial class CheckBox : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"text")]
    [global::System.ComponentModel.DefaultValue("")]
    public string Text { get; set; } = "";

    [global::ProtoBuf.ProtoMember(2, Name = @"type")]
    public CheckboxType Type { get; set; }

    [global::ProtoBuf.ProtoMember(3, Name = @"default_value")]
    public bool DefaultValue { get; set; }

    [global::ProtoBuf.ProtoMember(4, Name = @"show")]
    public bool Show { get; set; }

}

[global::ProtoBuf.ProtoContract()]
public partial class CheckBoxV2 : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"text")]
    [global::System.ComponentModel.DefaultValue("")]
    public string Text { get; set; } = "";

    [global::ProtoBuf.ProtoMember(2, Name = @"type")]
    public int Type { get; set; }

    [global::ProtoBuf.ProtoMember(3, Name = @"default_value")]
    public bool DefaultValue { get; set; }

}

[global::ProtoBuf.ProtoContract()]
public partial class ClickButton : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"portrait_text")]
    public global::System.Collections.Generic.List<string> PortraitTexts { get; } = new global::System.Collections.Generic.List<string>();

    [global::ProtoBuf.ProtoMember(2, Name = @"landscape_text")]
    public global::System.Collections.Generic.List<string> LandscapeTexts { get; } = new global::System.Collections.Generic.List<string>();

    [global::ProtoBuf.ProtoMember(3, Name = @"portrait_text_focus")]
    public global::System.Collections.Generic.List<string> PortraitTextFocus { get; } = new global::System.Collections.Generic.List<string>();

    [global::ProtoBuf.ProtoMember(4, Name = @"landscape_text_focus")]
    public global::System.Collections.Generic.List<string> LandscapeTextFocus { get; } = new global::System.Collections.Generic.List<string>();

    [global::ProtoBuf.ProtoMember(5, Name = @"render_type")]
    public RenderType RenderType { get; set; }

    [global::ProtoBuf.ProtoMember(6, Name = @"show")]
    public bool Show { get; set; }

    [global::ProtoBuf.ProtoMember(7, Name = @"bubble")]
    public Bubble Bubble { get; set; }

}

[global::ProtoBuf.ProtoContract()]
public partial class ClickButtonV2 : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"portrait_text")]
    public global::System.Collections.Generic.List<string> PortraitTexts { get; } = new global::System.Collections.Generic.List<string>();

    [global::ProtoBuf.ProtoMember(2, Name = @"landscape_text")]
    public global::System.Collections.Generic.List<string> LandscapeTexts { get; } = new global::System.Collections.Generic.List<string>();

    [global::ProtoBuf.ProtoMember(3, Name = @"portrait_text_focus")]
    public global::System.Collections.Generic.List<string> PortraitTextFocus { get; } = new global::System.Collections.Generic.List<string>();

    [global::ProtoBuf.ProtoMember(4, Name = @"landscape_text_focus")]
    public global::System.Collections.Generic.List<string> LandscapeTextFocus { get; } = new global::System.Collections.Generic.List<string>();

    [global::ProtoBuf.ProtoMember(5, Name = @"render_type")]
    public int RenderType { get; set; }

    [global::ProtoBuf.ProtoMember(6, Name = @"text_input_post")]
    public bool TextInputPost { get; set; }

    [global::ProtoBuf.ProtoMember(7, Name = @"exposure_once")]
    public bool ExposureOnce { get; set; }

    [global::ProtoBuf.ProtoMember(8, Name = @"exposure_type")]
    public int ExposureType { get; set; }

}

[global::ProtoBuf.ProtoContract()]
public partial class CommandDm : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"id")]
    public long Id { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"oid")]
    public long Oid { get; set; }

    [global::ProtoBuf.ProtoMember(3, Name = @"mid")]
    [global::System.ComponentModel.DefaultValue("")]
    public string Mid { get; set; } = "";

    [global::ProtoBuf.ProtoMember(4, Name = @"command")]
    [global::System.ComponentModel.DefaultValue("")]
    public string Command { get; set; } = "";

    [global::ProtoBuf.ProtoMember(5, Name = @"content")]
    [global::System.ComponentModel.DefaultValue("")]
    public string Content { get; set; } = "";

    [global::ProtoBuf.ProtoMember(6, Name = @"progress")]
    public int Progress { get; set; }

    [global::ProtoBuf.ProtoMember(7, Name = @"ctime")]
    [global::System.ComponentModel.DefaultValue("")]
    public string Ctime { get; set; } = "";

    [global::ProtoBuf.ProtoMember(8, Name = @"mtime")]
    [global::System.ComponentModel.DefaultValue("")]
    public string Mtime { get; set; } = "";

    [global::ProtoBuf.ProtoMember(9, Name = @"extra")]
    [global::System.ComponentModel.DefaultValue("")]
    public string Extra { get; set; } = "";

    [global::ProtoBuf.ProtoMember(10)]
    [global::System.ComponentModel.DefaultValue("")]
    public string idStr { get; set; } = "";

}

[global::ProtoBuf.ProtoContract()]
public partial class DanmakuAIFlag : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"dm_flags")]
    public global::System.Collections.Generic.List<DanmakuFlag> DmFlags { get; } = new global::System.Collections.Generic.List<DanmakuFlag>();

}

[global::ProtoBuf.ProtoContract()]
public partial class DanmakuElem : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"id")]
    public long Id { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"progress")]
    public int Progress { get; set; }

    [global::ProtoBuf.ProtoMember(3, Name = @"mode")]
    public int Mode { get; set; }

    [global::ProtoBuf.ProtoMember(4, Name = @"fontsize")]
    public int Fontsize { get; set; }

    [global::ProtoBuf.ProtoMember(5, Name = @"color")]
    public uint Color { get; set; }

    [global::ProtoBuf.ProtoMember(6)]
    [global::System.ComponentModel.DefaultValue("")]
    public string midHash { get; set; } = "";

    [global::ProtoBuf.ProtoMember(7, Name = @"content")]
    [global::System.ComponentModel.DefaultValue("")]
    public string Content { get; set; } = "";

    [global::ProtoBuf.ProtoMember(8, Name = @"ctime")]
    public long Ctime { get; set; }

    [global::ProtoBuf.ProtoMember(9, Name = @"weight")]
    public int Weight { get; set; }

    [global::ProtoBuf.ProtoMember(10, Name = @"action")]
    [global::System.ComponentModel.DefaultValue("")]
    public string Action { get; set; } = "";

    [global::ProtoBuf.ProtoMember(11, Name = @"pool")]
    public int Pool { get; set; }

    [global::ProtoBuf.ProtoMember(12)]
    [global::System.ComponentModel.DefaultValue("")]
    public string idStr { get; set; } = "";

    [global::ProtoBuf.ProtoMember(13, Name = @"attr")]
    public int Attr { get; set; }

    [global::ProtoBuf.ProtoMember(22, Name = @"animation")]
    [global::System.ComponentModel.DefaultValue("")]
    public string Animation { get; set; } = "";

}

[global::ProtoBuf.ProtoContract()]
public partial class DanmakuFlag : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"dmid")]
    public long Dmid { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"flag")]
    public uint Flag { get; set; }

}

[global::ProtoBuf.ProtoContract()]
public partial class DanmakuFlagConfig : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"rec_flag")]
    public int RecFlag { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"rec_text")]
    [global::System.ComponentModel.DefaultValue("")]
    public string RecText { get; set; } = "";

    [global::ProtoBuf.ProtoMember(3, Name = @"rec_switch")]
    public int RecSwitch { get; set; }

}

[global::ProtoBuf.ProtoContract()]
public partial class DanmuDefaultPlayerConfig : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"player_danmaku_use_default_config")]
    public bool PlayerDanmakuUseDefaultConfig { get; set; }

    [global::ProtoBuf.ProtoMember(4, Name = @"player_danmaku_ai_recommended_switch")]
    public bool PlayerDanmakuAiRecommendedSwitch { get; set; }

    [global::ProtoBuf.ProtoMember(5, Name = @"player_danmaku_ai_recommended_level")]
    public int PlayerDanmakuAiRecommendedLevel { get; set; }

    [global::ProtoBuf.ProtoMember(6, Name = @"player_danmaku_blocktop")]
    public bool PlayerDanmakuBlocktop { get; set; }

    [global::ProtoBuf.ProtoMember(7, Name = @"player_danmaku_blockscroll")]
    public bool PlayerDanmakuBlockscroll { get; set; }

    [global::ProtoBuf.ProtoMember(8, Name = @"player_danmaku_blockbottom")]
    public bool PlayerDanmakuBlockbottom { get; set; }

    [global::ProtoBuf.ProtoMember(9, Name = @"player_danmaku_blockcolorful")]
    public bool PlayerDanmakuBlockcolorful { get; set; }

    [global::ProtoBuf.ProtoMember(10, Name = @"player_danmaku_blockrepeat")]
    public bool PlayerDanmakuBlockrepeat { get; set; }

    [global::ProtoBuf.ProtoMember(11, Name = @"player_danmaku_blockspecial")]
    public bool PlayerDanmakuBlockspecial { get; set; }

    [global::ProtoBuf.ProtoMember(12, Name = @"player_danmaku_opacity")]
    public float PlayerDanmakuOpacity { get; set; }

    [global::ProtoBuf.ProtoMember(13, Name = @"player_danmaku_scalingfactor")]
    public float PlayerDanmakuScalingfactor { get; set; }

    [global::ProtoBuf.ProtoMember(14, Name = @"player_danmaku_domain")]
    public float PlayerDanmakuDomain { get; set; }

    [global::ProtoBuf.ProtoMember(15, Name = @"player_danmaku_speed")]
    public int PlayerDanmakuSpeed { get; set; }

    [global::ProtoBuf.ProtoMember(16, Name = @"inline_player_danmaku_switch")]
    public bool InlinePlayerDanmakuSwitch { get; set; }

    [global::ProtoBuf.ProtoMember(17, Name = @"player_danmaku_senior_mode_switch")]
    public int PlayerDanmakuSeniorModeSwitch { get; set; }

    [global::ProtoBuf.ProtoMember(18, Name = @"player_danmaku_ai_recommended_level_v2")]
    public int PlayerDanmakuAiRecommendedLevelV2 { get; set; }

    [global::ProtoBuf.ProtoMember(19, Name = @"player_danmaku_ai_recommended_level_v2_map")]
    [global::ProtoBuf.ProtoMap]
    public global::System.Collections.Generic.Dictionary<int, int> PlayerDanmakuAiRecommendedLevelV2Maps { get; } = new global::System.Collections.Generic.Dictionary<int, int>();

}

[global::ProtoBuf.ProtoContract()]
public partial class DanmuPlayerConfig : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"player_danmaku_switch")]
    public bool PlayerDanmakuSwitch { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"player_danmaku_switch_save")]
    public bool PlayerDanmakuSwitchSave { get; set; }

    [global::ProtoBuf.ProtoMember(3, Name = @"player_danmaku_use_default_config")]
    public bool PlayerDanmakuUseDefaultConfig { get; set; }

    [global::ProtoBuf.ProtoMember(4, Name = @"player_danmaku_ai_recommended_switch")]
    public bool PlayerDanmakuAiRecommendedSwitch { get; set; }

    [global::ProtoBuf.ProtoMember(5, Name = @"player_danmaku_ai_recommended_level")]
    public int PlayerDanmakuAiRecommendedLevel { get; set; }

    [global::ProtoBuf.ProtoMember(6, Name = @"player_danmaku_blocktop")]
    public bool PlayerDanmakuBlocktop { get; set; }

    [global::ProtoBuf.ProtoMember(7, Name = @"player_danmaku_blockscroll")]
    public bool PlayerDanmakuBlockscroll { get; set; }

    [global::ProtoBuf.ProtoMember(8, Name = @"player_danmaku_blockbottom")]
    public bool PlayerDanmakuBlockbottom { get; set; }

    [global::ProtoBuf.ProtoMember(9, Name = @"player_danmaku_blockcolorful")]
    public bool PlayerDanmakuBlockcolorful { get; set; }

    [global::ProtoBuf.ProtoMember(10, Name = @"player_danmaku_blockrepeat")]
    public bool PlayerDanmakuBlockrepeat { get; set; }

    [global::ProtoBuf.ProtoMember(11, Name = @"player_danmaku_blockspecial")]
    public bool PlayerDanmakuBlockspecial { get; set; }

    [global::ProtoBuf.ProtoMember(12, Name = @"player_danmaku_opacity")]
    public float PlayerDanmakuOpacity { get; set; }

    [global::ProtoBuf.ProtoMember(13, Name = @"player_danmaku_scalingfactor")]
    public float PlayerDanmakuScalingfactor { get; set; }

    [global::ProtoBuf.ProtoMember(14, Name = @"player_danmaku_domain")]
    public float PlayerDanmakuDomain { get; set; }

    [global::ProtoBuf.ProtoMember(15, Name = @"player_danmaku_speed")]
    public int PlayerDanmakuSpeed { get; set; }

    [global::ProtoBuf.ProtoMember(16, Name = @"player_danmaku_enableblocklist")]
    public bool PlayerDanmakuEnableblocklist { get; set; }

    [global::ProtoBuf.ProtoMember(17, Name = @"inline_player_danmaku_switch")]
    public bool InlinePlayerDanmakuSwitch { get; set; }

    [global::ProtoBuf.ProtoMember(18, Name = @"inline_player_danmaku_config")]
    public int InlinePlayerDanmakuConfig { get; set; }

    [global::ProtoBuf.ProtoMember(19, Name = @"player_danmaku_ios_switch_save")]
    public int PlayerDanmakuIosSwitchSave { get; set; }

    [global::ProtoBuf.ProtoMember(20, Name = @"player_danmaku_senior_mode_switch")]
    public int PlayerDanmakuSeniorModeSwitch { get; set; }

    [global::ProtoBuf.ProtoMember(21, Name = @"player_danmaku_ai_recommended_level_v2")]
    public int PlayerDanmakuAiRecommendedLevelV2 { get; set; }

    [global::ProtoBuf.ProtoMember(22, Name = @"player_danmaku_ai_recommended_level_v2_map")]
    [global::ProtoBuf.ProtoMap]
    public global::System.Collections.Generic.Dictionary<int, int> PlayerDanmakuAiRecommendedLevelV2Maps { get; } = new global::System.Collections.Generic.Dictionary<int, int>();

}

[global::ProtoBuf.ProtoContract()]
public partial class DanmuPlayerConfigPanel : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"selection_text")]
    [global::System.ComponentModel.DefaultValue("")]
    public string SelectionText { get; set; } = "";

}

[global::ProtoBuf.ProtoContract()]
public partial class DanmuPlayerDynamicConfig : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"progress")]
    public int Progress { get; set; }

    [global::ProtoBuf.ProtoMember(14, Name = @"player_danmaku_domain")]
    public float PlayerDanmakuDomain { get; set; }

}

[global::ProtoBuf.ProtoContract()]
public partial class DanmuPlayerViewConfig : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"danmuku_default_player_config")]
    public DanmuDefaultPlayerConfig DanmukuDefaultPlayerConfig { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"danmuku_player_config")]
    public DanmuPlayerConfig DanmukuPlayerConfig { get; set; }

    [global::ProtoBuf.ProtoMember(3, Name = @"danmuku_player_dynamic_config")]
    public global::System.Collections.Generic.List<DanmuPlayerDynamicConfig> DanmukuPlayerDynamicConfigs { get; } = new global::System.Collections.Generic.List<DanmuPlayerDynamicConfig>();

    [global::ProtoBuf.ProtoMember(4, Name = @"danmuku_player_config_panel")]
    public DanmuPlayerConfigPanel DanmukuPlayerConfigPanel { get; set; }

}

[global::ProtoBuf.ProtoContract()]
public partial class DanmuWebPlayerConfig : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"dm_switch")]
    public bool DmSwitch { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"ai_switch")]
    public bool AiSwitch { get; set; }

    [global::ProtoBuf.ProtoMember(3, Name = @"ai_level")]
    public int AiLevel { get; set; }

    [global::ProtoBuf.ProtoMember(4, Name = @"blocktop")]
    public bool Blocktop { get; set; }

    [global::ProtoBuf.ProtoMember(5, Name = @"blockscroll")]
    public bool Blockscroll { get; set; }

    [global::ProtoBuf.ProtoMember(6, Name = @"blockbottom")]
    public bool Blockbottom { get; set; }

    [global::ProtoBuf.ProtoMember(7, Name = @"blockcolor")]
    public bool Blockcolor { get; set; }

    [global::ProtoBuf.ProtoMember(8, Name = @"blockspecial")]
    public bool Blockspecial { get; set; }

    [global::ProtoBuf.ProtoMember(9, Name = @"preventshade")]
    public bool Preventshade { get; set; }

    [global::ProtoBuf.ProtoMember(10, Name = @"dmask")]
    public bool Dmask { get; set; }

    [global::ProtoBuf.ProtoMember(11, Name = @"opacity")]
    public float Opacity { get; set; }

    [global::ProtoBuf.ProtoMember(12, Name = @"dmarea")]
    public int Dmarea { get; set; }

    [global::ProtoBuf.ProtoMember(13, Name = @"speedplus")]
    public float Speedplus { get; set; }

    [global::ProtoBuf.ProtoMember(14, Name = @"fontsize")]
    public float Fontsize { get; set; }

    [global::ProtoBuf.ProtoMember(15, Name = @"screensync")]
    public bool Screensync { get; set; }

    [global::ProtoBuf.ProtoMember(16, Name = @"speedsync")]
    public bool Speedsync { get; set; }

    [global::ProtoBuf.ProtoMember(17, Name = @"fontfamily")]
    [global::System.ComponentModel.DefaultValue("")]
    public string Fontfamily { get; set; } = "";

    [global::ProtoBuf.ProtoMember(18, Name = @"bold")]
    public bool Bold { get; set; }

    [global::ProtoBuf.ProtoMember(19, Name = @"fontborder")]
    public int Fontborder { get; set; }

    [global::ProtoBuf.ProtoMember(20, Name = @"draw_type")]
    [global::System.ComponentModel.DefaultValue("")]
    public string DrawType { get; set; } = "";

    [global::ProtoBuf.ProtoMember(21, Name = @"senior_mode_switch")]
    public int SeniorModeSwitch { get; set; }

    [global::ProtoBuf.ProtoMember(22, Name = @"ai_level_v2")]
    public int AiLevelV2 { get; set; }

    [global::ProtoBuf.ProtoMember(23, Name = @"ai_level_v2_map")]
    [global::ProtoBuf.ProtoMap]
    public global::System.Collections.Generic.Dictionary<int, int> AiLevelV2Maps { get; } = new global::System.Collections.Generic.Dictionary<int, int>();

}

[global::ProtoBuf.ProtoContract()]
public partial class DmExpoReportReq : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"session_id")]
    [global::System.ComponentModel.DefaultValue("")]
    public string SessionId { get; set; } = "";

    [global::ProtoBuf.ProtoMember(2, Name = @"oid")]
    public long Oid { get; set; }

    [global::ProtoBuf.ProtoMember(4, Name = @"spmid")]
    [global::System.ComponentModel.DefaultValue("")]
    public string Spmid { get; set; } = "";

}

[global::ProtoBuf.ProtoContract()]
public partial class DmExpoReportRes : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

}

[global::ProtoBuf.ProtoContract()]
public partial class DmPlayerConfigReq : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"ts")]
    public long Ts { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"switch")]
    public PlayerDanmakuSwitch Switch { get; set; }

    [global::ProtoBuf.ProtoMember(3, Name = @"switch_save")]
    public PlayerDanmakuSwitchSave SwitchSave { get; set; }

    [global::ProtoBuf.ProtoMember(4, Name = @"use_default_config")]
    public PlayerDanmakuUseDefaultConfig UseDefaultConfig { get; set; }

    [global::ProtoBuf.ProtoMember(5, Name = @"ai_recommended_switch")]
    public PlayerDanmakuAiRecommendedSwitch AiRecommendedSwitch { get; set; }

    [global::ProtoBuf.ProtoMember(6, Name = @"ai_recommended_level")]
    public PlayerDanmakuAiRecommendedLevel AiRecommendedLevel { get; set; }

    [global::ProtoBuf.ProtoMember(7, Name = @"blocktop")]
    public PlayerDanmakuBlocktop Blocktop { get; set; }

    [global::ProtoBuf.ProtoMember(8, Name = @"blockscroll")]
    public PlayerDanmakuBlockscroll Blockscroll { get; set; }

    [global::ProtoBuf.ProtoMember(9, Name = @"blockbottom")]
    public PlayerDanmakuBlockbottom Blockbottom { get; set; }

    [global::ProtoBuf.ProtoMember(10, Name = @"blockcolorful")]
    public PlayerDanmakuBlockcolorful Blockcolorful { get; set; }

    [global::ProtoBuf.ProtoMember(11, Name = @"blockrepeat")]
    public PlayerDanmakuBlockrepeat Blockrepeat { get; set; }

    [global::ProtoBuf.ProtoMember(12, Name = @"blockspecial")]
    public PlayerDanmakuBlockspecial Blockspecial { get; set; }

    [global::ProtoBuf.ProtoMember(13, Name = @"opacity")]
    public PlayerDanmakuOpacity Opacity { get; set; }

    [global::ProtoBuf.ProtoMember(14, Name = @"scalingfactor")]
    public PlayerDanmakuScalingfactor Scalingfactor { get; set; }

    [global::ProtoBuf.ProtoMember(15, Name = @"domain")]
    public PlayerDanmakuDomain Domain { get; set; }

    [global::ProtoBuf.ProtoMember(16, Name = @"speed")]
    public PlayerDanmakuSpeed Speed { get; set; }

    [global::ProtoBuf.ProtoMember(17, Name = @"enableblocklist")]
    public PlayerDanmakuEnableblocklist Enableblocklist { get; set; }

    [global::ProtoBuf.ProtoMember(18)]
    public InlinePlayerDanmakuSwitch inlinePlayerDanmakuSwitch { get; set; }

    [global::ProtoBuf.ProtoMember(19, Name = @"senior_mode_switch")]
    public PlayerDanmakuSeniorModeSwitch SeniorModeSwitch { get; set; }

    [global::ProtoBuf.ProtoMember(20, Name = @"ai_recommended_level_v2")]
    public PlayerDanmakuAiRecommendedLevelV2 AiRecommendedLevelV2 { get; set; }

}

[global::ProtoBuf.ProtoContract()]
public partial class DmSegConfig : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"page_size")]
    public long PageSize { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"total")]
    public long Total { get; set; }

}

[global::ProtoBuf.ProtoContract()]
public partial class DmSegMobileReply : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"elems")]
    public global::System.Collections.Generic.List<DanmakuElem> Elems { get; } = new global::System.Collections.Generic.List<DanmakuElem>();

    [global::ProtoBuf.ProtoMember(2, Name = @"state")]
    public int State { get; set; }

    [global::ProtoBuf.ProtoMember(3, Name = @"ai_flag")]
    public DanmakuAIFlag AiFlag { get; set; }

}

[global::ProtoBuf.ProtoContract()]
public partial class DmSegMobileReq : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"pid")]
    public long Pid { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"oid")]
    public long Oid { get; set; }

    [global::ProtoBuf.ProtoMember(3, Name = @"type")]
    public int Type { get; set; }

    [global::ProtoBuf.ProtoMember(4, Name = @"segment_index")]
    public long SegmentIndex { get; set; }

    [global::ProtoBuf.ProtoMember(5, Name = @"teenagers_mode")]
    public int TeenagersMode { get; set; }

    [global::ProtoBuf.ProtoMember(6, Name = @"ps")]
    public long Ps { get; set; }

    [global::ProtoBuf.ProtoMember(7, Name = @"pe")]
    public long Pe { get; set; }

    [global::ProtoBuf.ProtoMember(8, Name = @"pull_mode")]
    public int PullMode { get; set; }

    [global::ProtoBuf.ProtoMember(9, Name = @"from_scene")]
    public int FromScene { get; set; }

}

[global::ProtoBuf.ProtoContract()]
public partial class DmSegOttReply : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"closed")]
    public bool Closed { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"elems")]
    public global::System.Collections.Generic.List<DanmakuElem> Elems { get; } = new global::System.Collections.Generic.List<DanmakuElem>();

}

[global::ProtoBuf.ProtoContract()]
public partial class DmSegOttReq : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"pid")]
    public long Pid { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"oid")]
    public long Oid { get; set; }

    [global::ProtoBuf.ProtoMember(3, Name = @"type")]
    public int Type { get; set; }

    [global::ProtoBuf.ProtoMember(4, Name = @"segment_index")]
    public long SegmentIndex { get; set; }

}

[global::ProtoBuf.ProtoContract()]
public partial class DmSegSDKReply : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"closed")]
    public bool Closed { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"elems")]
    public global::System.Collections.Generic.List<DanmakuElem> Elems { get; } = new global::System.Collections.Generic.List<DanmakuElem>();

}

[global::ProtoBuf.ProtoContract()]
public partial class DmSegSDKReq : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"pid")]
    public long Pid { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"oid")]
    public long Oid { get; set; }

    [global::ProtoBuf.ProtoMember(3, Name = @"type")]
    public int Type { get; set; }

    [global::ProtoBuf.ProtoMember(4, Name = @"segment_index")]
    public long SegmentIndex { get; set; }

}

[global::ProtoBuf.ProtoContract()]
public partial class DmViewReply : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"closed")]
    public bool Closed { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"mask")]
    public VideoMask Mask { get; set; }

    [global::ProtoBuf.ProtoMember(3, Name = @"subtitle")]
    public VideoSubtitle Subtitle { get; set; }

    [global::ProtoBuf.ProtoMember(4, Name = @"special_dms")]
    public global::System.Collections.Generic.List<string> SpecialDms { get; } = new global::System.Collections.Generic.List<string>();

    [global::ProtoBuf.ProtoMember(5, Name = @"ai_flag")]
    public DanmakuFlagConfig AiFlag { get; set; }

    [global::ProtoBuf.ProtoMember(6, Name = @"player_config")]
    public DanmuPlayerViewConfig PlayerConfig { get; set; }

    [global::ProtoBuf.ProtoMember(7, Name = @"send_box_style")]
    public int SendBoxStyle { get; set; }

    [global::ProtoBuf.ProtoMember(8, Name = @"allow")]
    public bool Allow { get; set; }

    [global::ProtoBuf.ProtoMember(9, Name = @"check_box")]
    [global::System.ComponentModel.DefaultValue("")]
    public string CheckBox { get; set; } = "";

    [global::ProtoBuf.ProtoMember(10, Name = @"check_box_show_msg")]
    [global::System.ComponentModel.DefaultValue("")]
    public string CheckBoxShowMsg { get; set; } = "";

    [global::ProtoBuf.ProtoMember(11, Name = @"text_placeholder")]
    [global::System.ComponentModel.DefaultValue("")]
    public string TextPlaceholder { get; set; } = "";

    [global::ProtoBuf.ProtoMember(12, Name = @"input_placeholder")]
    [global::System.ComponentModel.DefaultValue("")]
    public string InputPlaceholder { get; set; } = "";

    [global::ProtoBuf.ProtoMember(13, Name = @"report_filter_content")]
    public global::System.Collections.Generic.List<string> ReportFilterContents { get; } = new global::System.Collections.Generic.List<string>();

    [global::ProtoBuf.ProtoMember(14, Name = @"expo_report")]
    public ExpoReport ExpoReport { get; set; }

    [global::ProtoBuf.ProtoMember(15, Name = @"buzzword_config")]
    public BuzzwordConfig BuzzwordConfig { get; set; }

    [global::ProtoBuf.ProtoMember(16, Name = @"expressions")]
    public global::System.Collections.Generic.List<Expressions> Expressions { get; } = new global::System.Collections.Generic.List<Expressions>();

    [global::ProtoBuf.ProtoMember(17, Name = @"post_panel")]
    public global::System.Collections.Generic.List<PostPanel> PostPanels { get; } = new global::System.Collections.Generic.List<PostPanel>();

    [global::ProtoBuf.ProtoMember(18, Name = @"activity_meta")]
    public global::System.Collections.Generic.List<string> ActivityMetas { get; } = new global::System.Collections.Generic.List<string>();

    [global::ProtoBuf.ProtoMember(19, Name = @"post_panel2")]
    public global::System.Collections.Generic.List<PostPanelV2> PostPanel2s { get; } = new global::System.Collections.Generic.List<PostPanelV2>();

}

[global::ProtoBuf.ProtoContract()]
public partial class DmViewReq : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"pid")]
    public long Pid { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"oid")]
    public long Oid { get; set; }

    [global::ProtoBuf.ProtoMember(3, Name = @"type")]
    public int Type { get; set; }

    [global::ProtoBuf.ProtoMember(4, Name = @"spmid")]
    [global::System.ComponentModel.DefaultValue("")]
    public string Spmid { get; set; } = "";

    [global::ProtoBuf.ProtoMember(5, Name = @"is_hard_boot")]
    public int IsHardBoot { get; set; }

}

[global::ProtoBuf.ProtoContract()]
public partial class DmWebViewReply : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"state")]
    public int State { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"text")]
    [global::System.ComponentModel.DefaultValue("")]
    public string Text { get; set; } = "";

    [global::ProtoBuf.ProtoMember(3, Name = @"text_side")]
    [global::System.ComponentModel.DefaultValue("")]
    public string TextSide { get; set; } = "";

    [global::ProtoBuf.ProtoMember(4, Name = @"dm_sge")]
    public DmSegConfig DmSge { get; set; }

    [global::ProtoBuf.ProtoMember(5, Name = @"flag")]
    public DanmakuFlagConfig Flag { get; set; }

    [global::ProtoBuf.ProtoMember(6, Name = @"special_dms")]
    public global::System.Collections.Generic.List<string> SpecialDms { get; } = new global::System.Collections.Generic.List<string>();

    [global::ProtoBuf.ProtoMember(7, Name = @"check_box")]
    public bool CheckBox { get; set; }

    [global::ProtoBuf.ProtoMember(8, Name = @"count")]
    public long Count { get; set; }

    [global::ProtoBuf.ProtoMember(9)]
    public global::System.Collections.Generic.List<CommandDm> commandDms { get; } = new global::System.Collections.Generic.List<CommandDm>();

    [global::ProtoBuf.ProtoMember(10, Name = @"player_config")]
    public DanmuWebPlayerConfig PlayerConfig { get; set; }

    [global::ProtoBuf.ProtoMember(11, Name = @"report_filter_content")]
    public global::System.Collections.Generic.List<string> ReportFilterContents { get; } = new global::System.Collections.Generic.List<string>();

    [global::ProtoBuf.ProtoMember(12, Name = @"expressions")]
    public global::System.Collections.Generic.List<Expressions> Expressions { get; } = new global::System.Collections.Generic.List<Expressions>();

    [global::ProtoBuf.ProtoMember(13, Name = @"post_panel")]
    public global::System.Collections.Generic.List<PostPanel> PostPanels { get; } = new global::System.Collections.Generic.List<PostPanel>();

    [global::ProtoBuf.ProtoMember(14, Name = @"activity_meta")]
    public global::System.Collections.Generic.List<string> ActivityMetas { get; } = new global::System.Collections.Generic.List<string>();

}

[global::ProtoBuf.ProtoContract()]
public partial class ExpoReport : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"should_report_at_end")]
    public bool ShouldReportAtEnd { get; set; }

}

[global::ProtoBuf.ProtoContract()]
public partial class Expression : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"keyword")]
    public global::System.Collections.Generic.List<string> Keywords { get; } = new global::System.Collections.Generic.List<string>();

    [global::ProtoBuf.ProtoMember(2, Name = @"url")]
    [global::System.ComponentModel.DefaultValue("")]
    public string Url { get; set; } = "";

    [global::ProtoBuf.ProtoMember(3, Name = @"period")]
    public global::System.Collections.Generic.List<Period> Periods { get; } = new global::System.Collections.Generic.List<Period>();

}

[global::ProtoBuf.ProtoContract()]
public partial class Expressions : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"data")]
    public global::System.Collections.Generic.List<Expression> Datas { get; } = new global::System.Collections.Generic.List<Expression>();

}

[global::ProtoBuf.ProtoContract()]
public partial class InlinePlayerDanmakuSwitch : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"value")]
    public bool Value { get; set; }

}

[global::ProtoBuf.ProtoContract()]
public partial class Label : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"title")]
    [global::System.ComponentModel.DefaultValue("")]
    public string Title { get; set; } = "";

    [global::ProtoBuf.ProtoMember(2, Name = @"content")]
    public global::System.Collections.Generic.List<string> Contents { get; } = new global::System.Collections.Generic.List<string>();

}

[global::ProtoBuf.ProtoContract()]
public partial class LabelV2 : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"title")]
    [global::System.ComponentModel.DefaultValue("")]
    public string Title { get; set; } = "";

    [global::ProtoBuf.ProtoMember(2, Name = @"content")]
    public global::System.Collections.Generic.List<string> Contents { get; } = new global::System.Collections.Generic.List<string>();

    [global::ProtoBuf.ProtoMember(3, Name = @"exposure_once")]
    public bool ExposureOnce { get; set; }

    [global::ProtoBuf.ProtoMember(4, Name = @"exposure_type")]
    public int ExposureType { get; set; }

}

[global::ProtoBuf.ProtoContract()]
public partial class Period : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"start")]
    public long Start { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"end")]
    public long End { get; set; }

}

[global::ProtoBuf.ProtoContract()]
public partial class PlayerDanmakuAiRecommendedLevel : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"value")]
    public bool Value { get; set; }

}

[global::ProtoBuf.ProtoContract()]
public partial class PlayerDanmakuAiRecommendedLevelV2 : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"value")]
    public int Value { get; set; }

}

[global::ProtoBuf.ProtoContract()]
public partial class PlayerDanmakuAiRecommendedSwitch : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"value")]
    public bool Value { get; set; }

}

[global::ProtoBuf.ProtoContract()]
public partial class PlayerDanmakuBlockbottom : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"value")]
    public bool Value { get; set; }

}

[global::ProtoBuf.ProtoContract()]
public partial class PlayerDanmakuBlockcolorful : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"value")]
    public bool Value { get; set; }

}

[global::ProtoBuf.ProtoContract()]
public partial class PlayerDanmakuBlockrepeat : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"value")]
    public bool Value { get; set; }

}

[global::ProtoBuf.ProtoContract()]
public partial class PlayerDanmakuBlockscroll : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"value")]
    public bool Value { get; set; }

}

[global::ProtoBuf.ProtoContract()]
public partial class PlayerDanmakuBlockspecial : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"value")]
    public bool Value { get; set; }

}

[global::ProtoBuf.ProtoContract()]
public partial class PlayerDanmakuBlocktop : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"value")]
    public bool Value { get; set; }

}

[global::ProtoBuf.ProtoContract()]
public partial class PlayerDanmakuDomain : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"value")]
    public float Value { get; set; }

}

[global::ProtoBuf.ProtoContract()]
public partial class PlayerDanmakuEnableblocklist : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"value")]
    public bool Value { get; set; }

}

[global::ProtoBuf.ProtoContract()]
public partial class PlayerDanmakuOpacity : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"value")]
    public float Value { get; set; }

}

[global::ProtoBuf.ProtoContract()]
public partial class PlayerDanmakuScalingfactor : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"value")]
    public float Value { get; set; }

}

[global::ProtoBuf.ProtoContract()]
public partial class PlayerDanmakuSeniorModeSwitch : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"value")]
    public int Value { get; set; }

}

[global::ProtoBuf.ProtoContract()]
public partial class PlayerDanmakuSpeed : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"value")]
    public int Value { get; set; }

}

[global::ProtoBuf.ProtoContract()]
public partial class PlayerDanmakuSwitch : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"value")]
    public bool Value { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"can_ignore")]
    public bool CanIgnore { get; set; }

}

[global::ProtoBuf.ProtoContract()]
public partial class PlayerDanmakuSwitchSave : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"value")]
    public bool Value { get; set; }

}

[global::ProtoBuf.ProtoContract()]
public partial class PlayerDanmakuUseDefaultConfig : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"value")]
    public bool Value { get; set; }

}

[global::ProtoBuf.ProtoContract()]
public partial class PostPanel : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"start")]
    public long Start { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"end")]
    public long End { get; set; }

    [global::ProtoBuf.ProtoMember(3, Name = @"priority")]
    public long Priority { get; set; }

    [global::ProtoBuf.ProtoMember(4, Name = @"biz_id")]
    public long BizId { get; set; }

    [global::ProtoBuf.ProtoMember(5, Name = @"biz_type")]
    public PostPanelBizType BizType { get; set; }

    [global::ProtoBuf.ProtoMember(6, Name = @"click_button")]
    public ClickButton ClickButton { get; set; }

    [global::ProtoBuf.ProtoMember(7, Name = @"text_input")]
    public TextInput TextInput { get; set; }

    [global::ProtoBuf.ProtoMember(8, Name = @"check_box")]
    public CheckBox CheckBox { get; set; }

    [global::ProtoBuf.ProtoMember(9, Name = @"toast")]
    public Toast Toast { get; set; }

}

[global::ProtoBuf.ProtoContract()]
public partial class PostPanelV2 : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"start")]
    public long Start { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"end")]
    public long End { get; set; }

    [global::ProtoBuf.ProtoMember(3, Name = @"biz_type")]
    public int BizType { get; set; }

    [global::ProtoBuf.ProtoMember(4, Name = @"click_button")]
    public ClickButtonV2 ClickButton { get; set; }

    [global::ProtoBuf.ProtoMember(5, Name = @"text_input")]
    public TextInputV2 TextInput { get; set; }

    [global::ProtoBuf.ProtoMember(6, Name = @"check_box")]
    public CheckBoxV2 CheckBox { get; set; }

    [global::ProtoBuf.ProtoMember(7, Name = @"toast")]
    public ToastV2 Toast { get; set; }

    [global::ProtoBuf.ProtoMember(8, Name = @"bubble")]
    public BubbleV2 Bubble { get; set; }

    [global::ProtoBuf.ProtoMember(9, Name = @"label")]
    public LabelV2 Label { get; set; }

    [global::ProtoBuf.ProtoMember(10, Name = @"post_status")]
    public int PostStatus { get; set; }

}

[global::ProtoBuf.ProtoContract()]
public partial class Response : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"code")]
    public int Code { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"message")]
    [global::System.ComponentModel.DefaultValue("")]
    public string Message { get; set; } = "";

}

[global::ProtoBuf.ProtoContract()]
public partial class SubtitleItem : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"id")]
    public long Id { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"id_str")]
    [global::System.ComponentModel.DefaultValue("")]
    public string IdStr { get; set; } = "";

    [global::ProtoBuf.ProtoMember(3, Name = @"lan")]
    [global::System.ComponentModel.DefaultValue("")]
    public string Lan { get; set; } = "";

    [global::ProtoBuf.ProtoMember(4, Name = @"lan_doc")]
    [global::System.ComponentModel.DefaultValue("")]
    public string LanDoc { get; set; } = "";

    [global::ProtoBuf.ProtoMember(5, Name = @"subtitle_url")]
    [global::System.ComponentModel.DefaultValue("")]
    public string SubtitleUrl { get; set; } = "";

    [global::ProtoBuf.ProtoMember(6, Name = @"author")]
    public UserInfo Author { get; set; }

    [global::ProtoBuf.ProtoMember(7, Name = @"type")]
    public SubtitleType Type { get; set; }

    [global::ProtoBuf.ProtoMember(8, Name = @"lan_doc_brief")]
    [global::System.ComponentModel.DefaultValue("")]
    public string LanDocBrief { get; set; } = "";

    [global::ProtoBuf.ProtoMember(9, Name = @"ai_type")]
    public SubtitleAiType AiType { get; set; }

    [global::ProtoBuf.ProtoMember(10, Name = @"ai_status")]
    public SubtitleAiStatus AiStatus { get; set; }

}

[global::ProtoBuf.ProtoContract()]
public partial class TextInput : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"portrait_placeholder")]
    public global::System.Collections.Generic.List<string> PortraitPlaceholders { get; } = new global::System.Collections.Generic.List<string>();

    [global::ProtoBuf.ProtoMember(2, Name = @"landscape_placeholder")]
    public global::System.Collections.Generic.List<string> LandscapePlaceholders { get; } = new global::System.Collections.Generic.List<string>();

    [global::ProtoBuf.ProtoMember(3, Name = @"render_type")]
    public RenderType RenderType { get; set; }

    [global::ProtoBuf.ProtoMember(4, Name = @"placeholder_post")]
    public bool PlaceholderPost { get; set; }

    [global::ProtoBuf.ProtoMember(5, Name = @"show")]
    public bool Show { get; set; }

    [global::ProtoBuf.ProtoMember(6, Name = @"avatar")]
    public global::System.Collections.Generic.List<Avatar> Avatars { get; } = new global::System.Collections.Generic.List<Avatar>();

    [global::ProtoBuf.ProtoMember(7, Name = @"post_status")]
    public PostStatus PostStatus { get; set; }

    [global::ProtoBuf.ProtoMember(8, Name = @"label")]
    public Label Label { get; set; }

}

[global::ProtoBuf.ProtoContract()]
public partial class TextInputV2 : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"portrait_placeholder")]
    public global::System.Collections.Generic.List<string> PortraitPlaceholders { get; } = new global::System.Collections.Generic.List<string>();

    [global::ProtoBuf.ProtoMember(2, Name = @"landscape_placeholder")]
    public global::System.Collections.Generic.List<string> LandscapePlaceholders { get; } = new global::System.Collections.Generic.List<string>();

    [global::ProtoBuf.ProtoMember(3, Name = @"render_type")]
    public RenderType RenderType { get; set; }

    [global::ProtoBuf.ProtoMember(4, Name = @"placeholder_post")]
    public bool PlaceholderPost { get; set; }

    [global::ProtoBuf.ProtoMember(5, Name = @"avatar")]
    public global::System.Collections.Generic.List<Avatar> Avatars { get; } = new global::System.Collections.Generic.List<Avatar>();

    [global::ProtoBuf.ProtoMember(6, Name = @"text_input_limit")]
    public int TextInputLimit { get; set; }

}

[global::ProtoBuf.ProtoContract()]
public partial class Toast : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"text")]
    [global::System.ComponentModel.DefaultValue("")]
    public string Text { get; set; } = "";

    [global::ProtoBuf.ProtoMember(2, Name = @"duration")]
    public int Duration { get; set; }

    [global::ProtoBuf.ProtoMember(3, Name = @"show")]
    public bool Show { get; set; }

    [global::ProtoBuf.ProtoMember(4, Name = @"button")]
    public Button Button { get; set; }

}

[global::ProtoBuf.ProtoContract()]
public partial class ToastButtonV2 : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"text")]
    [global::System.ComponentModel.DefaultValue("")]
    public string Text { get; set; } = "";

    [global::ProtoBuf.ProtoMember(2, Name = @"action")]
    public int Action { get; set; }

}

[global::ProtoBuf.ProtoContract()]
public partial class ToastV2 : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"text")]
    [global::System.ComponentModel.DefaultValue("")]
    public string Text { get; set; } = "";

    [global::ProtoBuf.ProtoMember(2, Name = @"duration")]
    public int Duration { get; set; }

    [global::ProtoBuf.ProtoMember(3, Name = @"toast_button_v2")]
    public ToastButtonV2 ToastButtonV2 { get; set; }

}

[global::ProtoBuf.ProtoContract()]
public partial class UserInfo : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"mid")]
    public long Mid { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"name")]
    [global::System.ComponentModel.DefaultValue("")]
    public string Name { get; set; } = "";

    [global::ProtoBuf.ProtoMember(3, Name = @"sex")]
    [global::System.ComponentModel.DefaultValue("")]
    public string Sex { get; set; } = "";

    [global::ProtoBuf.ProtoMember(4, Name = @"face")]
    [global::System.ComponentModel.DefaultValue("")]
    public string Face { get; set; } = "";

    [global::ProtoBuf.ProtoMember(5, Name = @"sign")]
    [global::System.ComponentModel.DefaultValue("")]
    public string Sign { get; set; } = "";

    [global::ProtoBuf.ProtoMember(6, Name = @"rank")]
    public int Rank { get; set; }

}

[global::ProtoBuf.ProtoContract()]
public partial class VideoMask : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"cid")]
    public long Cid { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"plat")]
    public int Plat { get; set; }

    [global::ProtoBuf.ProtoMember(3, Name = @"fps")]
    public int Fps { get; set; }

    [global::ProtoBuf.ProtoMember(4, Name = @"time")]
    public long Time { get; set; }

    [global::ProtoBuf.ProtoMember(5, Name = @"mask_url")]
    [global::System.ComponentModel.DefaultValue("")]
    public string MaskUrl { get; set; } = "";

}

[global::ProtoBuf.ProtoContract()]
public partial class VideoSubtitle : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"lan")]
    [global::System.ComponentModel.DefaultValue("")]
    public string Lan { get; set; } = "";

    [global::ProtoBuf.ProtoMember(2)]
    [global::System.ComponentModel.DefaultValue("")]
    public string lanDoc { get; set; } = "";

    [global::ProtoBuf.ProtoMember(3, Name = @"subtitles")]
    public global::System.Collections.Generic.List<SubtitleItem> Subtitles { get; } = new global::System.Collections.Generic.List<SubtitleItem>();

}

[global::ProtoBuf.ProtoContract()]
public enum AvatarType
{
    AvatarTypeNone = 0,
    AvatarTypeNFT = 1,
}

[global::ProtoBuf.ProtoContract()]
public enum BubbleType
{
    BubbleTypeNone = 0,
    BubbleTypeClickButton = 1,
    BubbleTypeDmSettingPanel = 2,
}

[global::ProtoBuf.ProtoContract()]
public enum CheckboxType
{
    CheckboxTypeNone = 0,
    CheckboxTypeEncourage = 1,
    CheckboxTypeColorDM = 2,
}

[global::ProtoBuf.ProtoContract()]
public enum DMAttrBit
{
    DMAttrBitProtect = 0,
    DMAttrBitFromLive = 1,
    DMAttrHighLike = 2,
}

[global::ProtoBuf.ProtoContract()]
public enum ExposureType
{
    ExposureTypeNone = 0,
    ExposureTypeDMSend = 1,
}

[global::ProtoBuf.ProtoContract()]
public enum PostPanelBizType
{
    PostPanelBizTypeNone = 0,
    PostPanelBizTypeEncourage = 1,
    PostPanelBizTypeColorDM = 2,
    PostPanelBizTypeNFTDM = 3,
    PostPanelBizTypeFragClose = 4,
    PostPanelBizTypeRecommend = 5,
}

[global::ProtoBuf.ProtoContract()]
public enum PostStatus
{
    PostStatusNormal = 0,
    PostStatusClosed = 1,
}

[global::ProtoBuf.ProtoContract()]
public enum RenderType
{
    RenderTypeNone = 0,
    RenderTypeSingle = 1,
    RenderTypeRotation = 2,
}

[global::ProtoBuf.ProtoContract()]
public enum SubtitleAiStatus
{
    None = 0,
    Exposure = 1,
    Assist = 2,
}

[global::ProtoBuf.ProtoContract()]
public enum SubtitleAiType
{
    Normal = 0,
    Translate = 1,
}

[global::ProtoBuf.ProtoContract()]
public enum SubtitleType
{
    [global::ProtoBuf.ProtoEnum(Name = @"CC")]
    Cc = 0,
    [global::ProtoBuf.ProtoEnum(Name = @"AI")]
    Ai = 1,
}

[global::ProtoBuf.ProtoContract()]
public enum ToastFunctionType
{
    ToastFunctionTypeNone = 0,
    ToastFunctionTypePostPanel = 1,
}

[global::System.ServiceModel.ServiceContract(Name = @"bilibili.community.service.dm.v1.DM")]
public partial interface IDm
{
    global::System.Threading.Tasks.ValueTask<DmSegMobileReply> DmSegMobileAsync(DmSegMobileReq value, global::ProtoBuf.Grpc.CallContext context = default);
    global::System.Threading.Tasks.ValueTask<DmViewReply> DmViewAsync(DmViewReq value, global::ProtoBuf.Grpc.CallContext context = default);
    global::System.Threading.Tasks.ValueTask<Response> DmPlayerConfigAsync(DmPlayerConfigReq value, global::ProtoBuf.Grpc.CallContext context = default);
    global::System.Threading.Tasks.ValueTask<DmSegOttReply> DmSegOttAsync(DmSegOttReq value, global::ProtoBuf.Grpc.CallContext context = default);
    global::System.Threading.Tasks.ValueTask<DmSegSDKReply> DmSegSDKAsync(DmSegSDKReq value, global::ProtoBuf.Grpc.CallContext context = default);
    global::System.Threading.Tasks.ValueTask<DmExpoReportRes> DmExpoReportAsync(DmExpoReportReq value, global::ProtoBuf.Grpc.CallContext context = default);
}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
